# Generated by Django 5.2.1 on 2025-05-29 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "product_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images"
                    ),
                ),
                (
                    "current_price",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
        ),
    ]
